name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    env:
      CC: ${{matrix.cc}}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: gcc
            cc: gcc
            os: ubuntu-latest

          - name: clang
            cc: clang
            os: ubuntu-latest

          - name: clang-macOS
            cc: clang
            cxx: clang++
            os: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: System Information
        run: |
          awk -v a=$(uname) 'BEGIN { a == "Linux" ? system("cat /etc/issue") : system("sw_vers") }'
          ${CC} --version

      - name: Make
        run: |
          make

      - name: Build SF 0.01 data
        run: |
          ./dbgen -f -s 0.01 -k -b ./dists.dss

      - name: Generate queries
        run: |
          # With skew.
          ./qgen -k -s 0.01 -b ./dists.dss -r 123 -l params
          # Without skew.
          ./qgen -s 0.01 -b ./dists.dss -r 1234 -l params
