name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    env:
      CC: ${{matrix.cc}}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu-GCC
            cc: gcc
            os: ubuntu-latest

          - name: Ubuntu-Clang
            cc: clang
            os: ubuntu-latest

          - name: macOS-AppleClang
            cc: clang
            os: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: System Information
        run: |
          awk -v a=$(uname) 'BEGIN { a == "Linux" ? system("cat /etc/issue") : system("sw_vers") }'
          ${CC} --version

      - name: Make
        run: |
          CFLAGS="-Werror" make

      - name: Generate SF 0.01 Data
        run: |
          mkdir generated_data && cd generated_data
          # With skew.
          ../dbgen -f -s 0.01 -k -b ../dists.dss
          diff -r -q ../sample_data_sf-0.01/skewed .
          # Without skew.
          ../dbgen -f -s 0.01 -b ../dists.dss
          diff -r -q ../sample_data_sf-0.01/unskewed .

      - name: Generate Queries
        run: |
          mkdir generated_queries && cd generated_queries && ln -s ../queries/*.sql .
          # With skew and seed 123.
          ../qgen -k -s 0.01 -b ../dists.dss -r 123 -l params_skewed > /dev/null
          diff ../sample_params_sf-0.01/params_skewed_seed-123 params_skewed
          # Without skew and seed 1234.
          ../qgen -s 0.01 -b ../dists.dss -r 1234 -l params_unskewed > /dev/null
          diff ../sample_params_sf-0.01/params_unskewed_seed-1234 params_unskewed
